vmware/ansible-for-nsxt

- library/nsxt_compute_collection_transport_templates.py
nsxt_compute_collection_transport_templates.py was failing when the template has already been created by a previous run. This was because
a function named id_exist_in_list_dict_obj was called but not defined.
The function is defined now. This solves issue #33.
> nsxt_compute_collection_transport_template bu

- library/nsxt_deploy_ova.py
Deployment size was not getting initialized as
per user needs. The issue is corrected now.
Problem: Deployment size was having port group
dependency on it. It port group was not being
mentioned explicitly then the deployment size was set to medium by default.
Signed-off-by: akhileshk <akhileshk@vmware.com>
> Deployment size issue

- library/nsxt_deploy_ova.py
The connection was insecure. We were using 
SSL version sslv23 and verify mode CERT_NONE.
This would cause the connection to go through
even if vCenter doesn't provide a valid certificate.
The bug is solved now. The SSL version has been
updated to TLSv1.2 and the default server certificate
is being loaded now.
> Bug insecure ssl connection

- README.md
- answerfile.yml
- library/nsxt_certificates.py
- library/nsxt_principal_identities.py
- module_utils/vmware_nsxt.py
- test_certificates.yml
- test_principal_identities.yml
1. Now all clients can access API services using their self signed certificates.
2. The process of authentication and the creation
of the client certificates is mentioned in README.md file.
3. It is kept in mind that the previous method
of basic authentication works without any problem.
> Added certificate based authentication

- library/nsxt_controller_manager_auto_deployment.py
- library/nsxt_edge_clusters.py
- library/nsxt_transport_nodes.py
- module_utils/vcenter_utils.py
- module_utils/vmware_nsxt.py
1. Module: nsxt_transport_nodes
Calculating the thumbprinting and expect the user to enter one.
2. Module: nsxt_edge_clusters -
Calculating cluster-profile-id based on Cluster-profile-name
3. Module: nsxt_transport_nodes
Calculating VC id from VC name
Calculating host id from host name
Calculating storage id from datastore name
Calculating data network and management network id from respective names
User need to add vcenter username and password if he doesn't then works as before
4. Module: nsxt_controller_manager_auto_deployment
Calculating VC id from VC name
Calculating host id from host name
Calculating storage id from datastore name
Calculating data network and management network id from respective names
User need to add vcenter username and password if he doesn't then works as before
> Thumbprint, profile name and vC resources ids

- module_utils/vcenter_utils.py
- test_edge_clusters.yml
- SSLContext attribute was not supported in python versions
earlier than 2.7.9. Thus, caused errors with vCenter utils.
The support is now added for all python 2.7 all versions.
- Playbook file test_edge_cluster was not updated. The
parameter it takes are updated.
> SSLContext support and correction in edge cluster playbook

- library/nsxt_transport_node_profiles.py
The default endpoint path of `/host-switch-profiles` does not return _system_owned objects.
Added `include_system_owned=true` and fixed a couple of minor issues with error messages.
Signed-off-by: Alex Feigenson <alex.feigenson@gmail.com>
> Fixes issue #70

- library/nsxt_deploy_ova.py
- library/nsxt_transport_node_profiles.py
Currently, nsx_deploy_ova module was using SSLv23 while connecting to
vCenter. This is now upgraded to TLSv1.2.
> Upgrading SSL protocol for nsx_deploy_ova modules

- policy-ansible-for-nsxt/examples/01_create_t0_gateway.yml
- policy-ansible-for-nsxt/examples/build_topology_vars.yml
- policy-ansible-for-nsxt/library/nsxt_ip_block.py
- policy-ansible-for-nsxt/library/nsxt_ip_pool.py
- policy-ansible-for-nsxt/library/nsxt_policy_group.py
- policy-ansible-for-nsxt/library/nsxt_security_policy.py
- policy-ansible-for-nsxt/library/nsxt_segment.py
- policy-ansible-for-nsxt/library/nsxt_tier0.py
- policy-ansible-for-nsxt/library/nsxt_tier1.py
- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
- policy-ansible-for-nsxt/tests/unit/module_utils/test_nsxt_base_resource.py
Until now, user had to prepent a prefix to specify any subresource
spec in the playbook. This limited the user's scope to specify only
1 subresource. However, it is possible that 2 or more subresources
can be associated with a single resource. This change
modifies the behavior in a way that the user can specify multiple
subresources under its respective section, which is clear from the
Ansible Module's doc.
Additionally, there are some speed enhancements:
1. We no longer create an Ansible Module for each subresource
2. We no longer test and create Ansible Module to infer which
resources are specified by the user at runtime. This is possible
with the help of using spec_identifiers
Lastly, using spec_identifiers improves the code readability as well
as user experience.
Issue: #123 …
> Enhancement: Support sub-resource list specifications

- library/nsxt_fabric_compute_managers.py
nsxt_fabric_compute_managers was ending up with error of compute
manager status DOWN while adding compute manager. Compute manager
status is shown down for few secs before it gets UP. The module
was exiting with error in the meantime. The issue is resolved now
with this change.
> nsxt_fabric_compute_manager bug fix

- library/nsxt_uplink_profiles.py
Description field was not present in nsxt_uplink_profiles
module. The support for the field is added now in the
module. This solves bugzilla #2509025.
> Description field in nsxt_uplink_profiles

- library/nsxt_transport_zones.py
Transport zone update was failing even when description was
being changed. This was due to incorrect way of checking for
update. It is fixed now. This solves bugzilla #2508917
> Transport zone update

- library/nsxt_fabric_compute_managers.py
- module_utils/vmware_nsxt.py
Delete task of nsxt_fabric_compute_manager was failing as
error code was not being returned was not caught in
python 3.6. The issue is solved now.
This was the reason that update failed as response returned
was '' rather than dict.
Added support for description parameter.
This solves bugzilla #2508958, #2510222, #251023
> Compatibility python 3.6

- library/nsxt_manager_auto_deployment.py
- library/nsxt_manager_auto_deployment_facts.py
- test_manager_auto_deployment.yml
- test_manager_auto_deployment_facts.yml
Autodeployment modules of have been renamed
nsxt_controller_manager_auto_deployment is changed to
nsxt_manager_auto_deployment.
nsxt_controller_manager_auto_deployment_facts is changed
to nsx_manager_auto_deployment_facts.
This solves bugzilla 2510151
> Renaming auto_deployment modules

- library/nsxt_transport_node_profiles.py
NSX Grindcore supports parameter transport_zone_endpoint
inside host_switch spec. This caused ansible break.
This PR gives support for the transport_zone_endpoint
parameter.
> Transport zone endpoint in host switch

- library/nsxt_transport_nodes.py
NSX Grindcore supports parameter transport_zone_endpoint
inside host_switch_spec, This caused nsxt_transport_nodes
module to fail. This CL fixes the issue.
> Transport zone endpoint in Transport Node module

- library/nsxt_transport_node_profiles.py
DHCP IP assignment option was not working for
"nsxt_transport_node_profiles" module. This was because when using
DHCP assignment, no IP pool is provided. Added null check. Thus,
solving the bugzilla issue #2518085.
> DHCP Assignment failure

- library/nsxt_uplink_profiles.py
Name field in teaming is not supported anymore. To add multiple
modules we use named_teaming option. Using name field throws
error from the Json error from manager. Thus removing the
field now. This solves bugzilla 2516146
> nsxt_uplink_profiles failing

- library/nsxt_transport_zones.py
Uplink teaming policy names field was unable to update to a
typing mistake in previous CL. The comparision was not done correctly.
During update existing_transport_zone was being compared with
existing_transport_zone. Corrected the issue now. Comparing
existing_transport_zone with transport_zone_params.
Tested: uplink teaming_policy_names are updated successfully.
> Existing transport zone update

- policy-ansible-for-nsxt/library/nsxt_policy_group.py
- policy-ansible-for-nsxt/library/nsxt_security_policy.py
These attributes can be provided by the user to configure the
resources on NSX and hence must be included.
> Add missing attrs in policy_group and securty_policy

- policy-ansible-for-nsxt/README.md
- policy-ansible-for-nsxt/library/nsxt_tier0.py
- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
We reuse the nsxt_tier0 module to add the support to configure
the vrf_config on a tier0 router
Jira: #50034
> Add support for vrf_config in tier0

- policy-ansible-for-nsxt/library/nsxt_segment.py
- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_segment.yml
These attributes can be configured using the API and hence must
be added to the Ansible Playbook configuration so that they
can be specified by the user.
> Add missing attrs in nsxt_segment and seg_ports

- policy-ansible-for-nsxt/library/nsxt_ip_block.py
- policy-ansible-for-nsxt/library/nsxt_ip_pool.py
- policy-ansible-for-nsxt/library/nsxt_policy_group.py
- policy-ansible-for-nsxt/library/nsxt_security_policy.py
- policy-ansible-for-nsxt/library/nsxt_segment.py
- policy-ansible-for-nsxt/library/nsxt_tier0.py
- policy-ansible-for-nsxt/library/nsxt_tier1.py
- policy-ansible-for-nsxt/plugins/doc_fragments/vmware_nsxt.py
doc_fragments support is only available in collections. So, when we
move to Ansible collections, we will use vmware_nsxt to create
the Ansible module documentation. Until then, we add all the fields
in the DOCUMENTATION to each module.
> Add vmware_nsxt args to each module

- library/nsxt_fabric_compute_managers.py
Check for update method was not well written when description
field was added to the nsxt_fabric_compute_manager module.
This caused failure of module when using the module without
description field. Github issue #190 is solved in this PR.
Testing done:
- Deployed VC without providing Compute manager description. It
deployed successful.
- Added description to existing VC with no description.
- Modified existing description.
Signed-off-by: Kommireddy Akhilsh<akhileshkommireddy2412@gmail.com>
> nsxt_fabric_compute_manager description key error

- library/nsxt_principal_identities.py
Principal identity used deprecated API as per the code. Now using
the non deprecated API. Given that all the fields of two API are
same thus no need to change any of the params.
Signed-of-by: Kommireddy Akhilesh<akhileshkommireddy2412@gmail.com>
> Principal identity used deprecated API

- library/nsxt_manager_auto_deployment.py
- library/nsxt_principal_identities.py
Support for node_id and node_name are added while
deleting the autodeployed manager node. The priority of deletion
is node_id followed by node_name.
Principal id module
Principal id if already exists then made to exit gracefully.
> Adding support for node_id, node_name

- library/nsxt_upgrade_prechecks.py
Upgrade pre check was failing to retrieve data from an API,
as API was responding in csv format. This issue is not
happening in python 2 but occurring in Python3 due to
type changes in python3 response.
Given that there were previous suggestions about not showing
csv format on the ansible output as it is confusing. Showing
the upgrade results from upgrade/pre-upgrade-checks/failures
rather than upgrade/pre-upgrade-checks?format=csv
This works from both versions of python 2 and 3.
> Upgrade pre check break

- library/nsxt_edge_clusters.py
- library/nsxt_transport_node_profiles.py
Host switch id is automatically being taken from host switch name
when host switch type is VDS.
Updated logic for adding and removing of a edge TN from edge TN
cluster.
> Host switch id automatically being taken for VDS switch

- library/nsxt_edge_clusters.py
Issue occurred while resolving conflict on edge cluster module.
The return value was not passed correctly, hence causing the
break where python file was failing to compile. the issue is
fixed in this CL.
> Edge Cluster Unloadable

- library/nsxt_transport_nodes.py
Node deplyment info revision is a mandatory field while updating
a transport node. Previously the node deployment info being passed
was same as the resource revision as in most of the cases they
are same. Now node deployment info revision is passed after
retrieving the current revision.
> Adding node deployment info revision

- README.md
- module_utils/policy_communicator.py
.p12 certificates are used in MP based Ansible Modules. Before we
can merge Policy into MP, Policy modules must support .p12
certificates as well.
> Add support for .p12 certificate

- library/nsxt_ip_blocks.py
- library/nsxt_ip_blocks_facts.py
- library/nsxt_ip_pools.py
- library/nsxt_logical_switches_facts.py
- library/nsxt_transport_nodes.py
- test_ip_blocks.yml
- test_ip_blocks_facts.yml
There were issues with IP pools.
1. Tags param was in format of str instead of list causing module
to fail.
2. Optional params description and ip_release_delay were added.
Corrected transport node example
Facts module of logical switch was calling incorrect API. Corrected.
Playbook files added for IP block modules.
> IP Pools and blocks issues

- policy-ansible-for-nsxt/README.md
Since the dev branch includes some H changes as well, we need to
ensure the minimum Ansible required version matches H.
> Update Min Ansible required version

- library/nsxt_upgrade_postchecks.py
post upgrade checks module was not auto quitting. This is because
we were not checking if the component is upgraded or not and also
we were not checking if upgrade unit exists in the upgrade
group.
> Post upgrade checks not quitting

- library/nsxt_logical_ports.py
- library/nsxt_logical_switches.py
Problems existed with nsxt_logical_port and nsxt_logical_switches.
While converting switching-profile-name to id wrong api
endpoint was being used. The API endpoint is corrected now.
> nsxt_logical_port and nsxt_logical_switches correction

- library/nsxt_logical_switches.py
Ansible doesn't have boolean type. The keyword for it is
bool. hybrid param in nsxt_logical_switches module had
param as boolean. Thus failing the parameter. Changed it
to bool.
> Unsupported param type boolean in nsxt_logical_switcches

- library/nsxt_logical_switches.py
nsxt_logical_switches was using mac_pool_id. Added support for
mac_pool_name. If both mac_pool_id and mac_pool_name are given
priority is given to mac_pool_id.
> Adding support for mac_pool_name in nsx_logical_switches

- library/nsxt_logical_router_ports.py
Added support to convert target_display_name to target_id in
linked_logical_switch_port_id dict. The functionality
implemented will give more priority if target_id is given.
If target_display_name is given and target_id is not, then
then only target_id field will be added.
> Converting logical_port name to id

- library/nsxt_policy_segment.py
address_pool can be specified as id or display_name. Since it's
optional, it can also not be specified. In the latter case, we
should not try to infer the address_pool_path
Issue: #253
> Fix optional address_pool in Segment

- module_utils/nsxt_base_resource.py
- module_utils/policy_communicator.py
The user needs to specify the authentication credentials that will
be used to communicate to the NSX Manager. If these credentials
are incorrect, the module should gracefully exit while initimating
the user about it.
> Gracefully exit upon unexpected error from Manager

- module_utils/nsxt_base_resource.py
- module_utils/policy_communicator.py
policy_communicator module should always raise an Exception that has
args of form (return_code, data)
Issue: #267
> Return error_code from policy-communicator upon failure

- library/nsxt_policy_segment.py
If the user does not specify TZ, then it's atts that are read from
the playbook are still sent to API server which results in an
error
> Fix Segment TZ optional attrs

- library/nsxt_policy_tier0.py
- library/nsxt_policy_tier1.py
route_redistribution_types is present in LocaleService
Issue: #2546726
> Support deprecated attr - route_redistribution_types

- library/nsxt_upgrade_prechecks.py
Before on a upgrade precheck error, we used to show error and
not fail the module. Now, on precheck error we fail the module.
The module proceeds on WARNING.
Signed-off-by: Kommireddy Akhilesh <akhileshkommireddy2412@gmail.com>
> Fail on precheck failure

- library/nsxt_transport_node_profiles.py
This adds vmkernel interface migration support to nsxt_transport_node_profiles
Tested with NSX-T 3.0
> Add vmk install migration support in Transport Node Profiles

- library/nsxt_fabric_compute_managers.py
Add support for set_as_oidc_provider to 
nsxt_fabric_compute_managers. This flag is required
to be enabled for NSX-T 3.0 integration with TKGS,
also know as Kubernetes on vSphere.
Tested working, plus tested that an update will be triggered by updating the flag.
Signed-off-by: Matt Proud <matt.proud@gmail.com>
> Add support for set_as_oidc_provider to compute manager

- library/nsxt_policy_segment.py
- module_utils/nsxt_base_resource.py
We should remove empty params from request body while making PATCH
call if the same attrs are not set already on the resource.
Otherwise, we assume that there is a PATCH operation
being done on it while in reality, there is None.
Eg. Policy API returns a response in which None attrs are not set.
When we create the user request body, we set attrs to None. Although
both mean semantically the same, the syntax difference makes us
assume that a PATCH call should be done
Issue: #317
> Remove empty params for req body

- module_utils/nsxt_base_resource.py
In some cases, it is not possible to infer if a PATCH call should
be made on the NSX-t resource. This is because Ansible substitues
missing keys with None. We always send the PATCH call in such cases.
If the server updates the resource, it's revision is updated and
we check it to infer if it was updated actually.
Issue: #2658008
> Verify resource was updated after PATCH

- library/nsxt_policy_segment.py
It is raised when one of address_pool_id or address_pool_display_name
is specified. With patch 054d5b1, we don't need the instructions that
remove the other key from request body which is not specified.
Issue: #2667627
> Fix invalid key error in policy segment

- library/nsxt_policy_tier0.py
- library/nsxt_policy_tier1.py
- module_utils/nsxt_base_resource.py
- tests/unit/module_utils/test_nsxt_base_resource.py
- tests/unit/module_utils/test_policy_communicator.py
One of them must be specified by the user to guarantee correct
execution.
Additionally, fix some UTs
Issue: #2655610
> Make either id or display_name required

- library/nsxt_policy_tier0.py
- library/nsxt_policy_tier1.py
- module_utils/nsxt_base_resource.py
LocaleService is automatically created by NSX when the user tries
to do some operation on tier0/1 like set the Edge Cluster. In such cases,
the ID cannot be known by the user as they only have access to UI.
Therefore, if it cannot be specified we use the existing LocaleService
on the gateway and configure that.
If no LocaleService was present but user didn't specify ID or display_name,
then error is thrown to provide either of them
If multiple LocaleServices are present, error is thrown to specify the exact
LocaleService ID.
Issue: #2655611
> Infer LocaleService ID automatically if precreated

- library/nsxt_policy_tier0.py
The user can use bfd_profile_id or bfd_profile_display_name to specify it
which are much easier and better to use
Issue: #2673060
> Disallow specifying bfd_profile_path

- library/nsxt_rest.py
- test_rest.yml
This PR adds a module that directly accesses and executes the NSX REST API.
NSX-T is so multifunctional that the existing Ansible modules are insufficient to do everything.
This module is useful for running ranges that are not covered by existing Ansible modules.
* New Module Pull Request
nsxt_rest
tested with NSXT-3.0
If the branch to pull request is wrong, could you tell me the appropriate branch?
> add new nsxt module nsxt_rest

- library/nsxt_edge_clusters.py
Current nsxt_edge_clusters module always registers a change because edge cluster member detection was not fully developed.
With NSX-T 3.1 (and probably other versions) the API returns a member index key/value for each member. This fix checks each member one at a time to match the transport_node_ids.
Signed-off-by: Matt Proud proudmatt@gmail.com
> Fix to make nsxt_edge_clusters idempotent

- README.md
- module_utils/vmware_nsxt.py
To validate ceritificate authority (CA), set NSX_MANAGER_CA_PATH
environment variable on Ansible control node pointing
to CA certificate of NSX manager and pass validate_certs
as True in ansible playbook.
Signed-off-by: Rahul Raghuvanshi <rraghuvanshi@vmware.com>
> CA validation MP modules

- plugins/module_utils/nsxt_base_resource.py
- plugins/modules/nsxt_policy_segment.py
With the last update to fetch all the resources from NSX accounting
for pagination, the logic to infer ID from display_name of a resource
specified in the Ansible spec broke. This patch fixes it
Issue: #371
> Fix inferring res ID from display_name

- plugins/modules/nsxt_logical_routers.py
- plugins/modules/nsxt_upgrade_run.py
- tests/playbooks/mp/test_logical_routers.yml
Description:
The following bugs were fixed in this commit.
2654045 - Updation of certain fields are not supported by 'nsxt_logical_routers' module 2687520 - upgrade module 'nsxt_upgrade_run' gets stuck even after MP upgrade completion is 100 percent. and edge upgrade status is cleared from from 100% to 0.0 2634460 - ID should be replace with name for "redundant_uplink_port_ids" under "ha_vip_configs" in "nsxt_logical_routers" module
> Multiple Bugfixes

- plugins/module_utils/vcenter_utils.py
- plugins/modules/nsxt_edge_clusters.py
Fix for nsxt_edge_clusters throws error if existing cluster and new cluster are different.
Enhancement made to vcenter_utils.py file.
Following bugs are fixed -
BugID     Description
2923954 - nsxt_edge_clusters module throws "Existing [xxx] new [yyy]" error if cluster members are in unexpected order
> Fix for nsxt_edge_clusters throws error if existing cluster and new cluster are different.

- plugins/module_utils/nsxt_resource_urls.py
- plugins/module_utils/policy_communicator.py
- plugins/modules/nsxt_vm_tags.py
This updates `nsxt_vm_tags` to use an API that is not deprecated and supports query parameters so that environments with over 1000 VMs work.
This also resolves an issue I was having where tags with the same scope were having their tags overwritten by values from other tags in the same scope.
This should resolve #438 and #395. It might also resolve #392.
> Fix vm tagging for large environments

- .gitignore
- plugins/module_utils/vmware_nsxt.py
- plugins/modules/nsxt_logical_switches.py
MP support has been deprecated in NSX v9.x, so validate that NSX is running below this version on logical switch MP.
> Check NSX version to detect MP support
