- examples/deploy_nsx_cluster/01_deploy_first_node.yml
- examples/deploy_nsx_cluster/02_configure_compute_manager.yml
- examples/deploy_nsx_cluster/03_deploy_second_third_node.yml
- examples/deploy_nsx_cluster/README.md
- examples/deploy_nsx_cluster/deploy_nsx_cluster_vars.yml
Validated by deploying a full Cluster.
> Deploy NSX-T cluster example

- README.md
- answerfile.yml
- library/nsxt_route_advertise.py
- test_route_advertise.yml
Added a module and example to allow setting route advertisement on a tier 0 router.
Signed-off-by: Matt Proud <proudmatt@gmail.com>
> Added route advertise

- examples/setup_infra/01_deploy_transport_zone.yml
- examples/setup_infra/02_define_TEP_IP_Pools.yml
- examples/setup_infra/03_create_transport_node_profiles.yml
- examples/setup_infra/04_create_edge_node.yml
- examples/setup_infra/05_create_edge_cluster.yml
- examples/setup_infra/setup_infra_vars.yml
- library/nsxt_transport_node_profiles.py
- library/nsxt_transport_nodes.py
An example to create Transport Zones, Edge Nodes and Edge Cluster as a Day 0/1 operation
> Day-0/1 operations: Create TZ, Edge TN and Edge Cluster

- library/nsxt_fabric_compute_managers.py
Added no_log argument. This solves github bug #61.
> Password was being shown in nsx_fabric_compute_manager

- README.md
Updated changes of generating certificate in
README.md
> Changed commands to generate certificate

- library/nsxt_virtual_ip.py
- library/nsxt_virtual_ip_facts.py
- module_utils/common_utils.py
- test_virtual_ip.yml
- test_virtual_ip_facts.yml
Created module for cluster virtual IP.
Added modules include nsxt_virtual_ip
and nsxt_virtual_ip_facts.
> Modules for cluster VIP

- library/nsxt_repo_sync.py
- library/nsxt_repo_sync_facts.py
- module_utils/common_utils.py
- module_utils/vmware_nsxt.py
- test_repo_sync.yml
- test_repo_sync_facts.yml
Added get status module and sync repo module
> Added modules for repo sync

- policy-ansible-for-nsxt/module_utils/policy_edge_cluster.py
- policy-ansible-for-nsxt/module_utils/policy_edge_node.py
Fix issue https://github.com/vmware/ansible-for-nsxt/issues/98
> Fix to create tier0 gateway

- examples/deploy_nsx_cluster/01_deploy_first_node.yml
> Fix compute_manager reference

- policy-ansible-for-nsxt/examples/01_create_t0_gateway.yml
- policy-ansible-for-nsxt/examples/02_create_t1_gateway.yml
- policy-ansible-for-nsxt/examples/03_create_segments.yml
- policy-ansible-for-nsxt/examples/04_create_groups.yml
- policy-ansible-for-nsxt/examples/05_create_security_policy.yml
- policy-ansible-for-nsxt/examples/README.md
- policy-ansible-for-nsxt/examples/build_topology.yml
- policy-ansible-for-nsxt/examples/build_topology_vars.yml
- policy-ansible-for-nsxt/examples/cleanup_topology.yml
> examples for day-1 config

- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
Previously, display_name had to be specified for any nested resource
specification. Now, either id or display_name must be specified if
the resource 'state' is specified.
Issue: #124
Additionally:
- Includes some minor improvements related to check_mode.
- id or display_name must be specified for the base resource.
> Make display_name optional in nested resources

- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
> Fix: Make id or display_name optional but either to be present

- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
> Fix: When resource spec is empty, do not try to modify resource

- policy-ansible-for-nsxt/README.md
> Updating readme with new resources that can be modified

- library/nsxt_transport_nodes.py
Added support of reservation_info field and reseource allocation
fields while deploying Edge transport node.
> Reservation info support in EdgeTN

- examples/deploy_nsx_cluster/01_deploy_first_node.yml
- examples/deploy_nsx_cluster/02_configure_compute_manager.yml
- examples/deploy_nsx_cluster/03_deploy_second_third_node.yml
- examples/deploy_nsx_cluster/README.md
- examples/deploy_nsx_cluster/deploy_nsx_cluster_vars.yml
- examples/setup_infra/01_setup_transport_zones.yml
- examples/setup_infra/02_setup_TEP_IP_Pools.yml
- examples/setup_infra/03_setup_transport_node_profiles.yml
- examples/setup_infra/04_setup_transport_nodes.yml
- examples/setup_infra/05_setup_edge_cluster.yml
- examples/setup_infra/README.md
- examples/setup_infra/setup_infra_vars.yml
- examples/upgrade/01_upgrade_upload_mub.yml
- examples/upgrade/02_upgrade_accept_eula.yml
- examples/upgrade/03_upgrade_uc.yml
- examples/upgrade/04_upgrade_update_plan.yml
- examples/upgrade/05_upgrade_update_groups.yml
- examples/upgrade/06_upgrade_prechecks.yml
- examples/upgrade/07_upgrade_run.yml
- examples/upgrade/README.md
- examples/upgrade/check_upgrade_groups_facts.yml
- examples/upgrade/check_upgrade_pre_post_checks_facts.yml
- examples/upgrade/check_upgrade_status_summary_facts.yml
- examples/upgrade/upgrade_vars.yml
- library/nsxt_fabric_compute_managers.py
- library/nsxt_manager_status.py
Added examples for Install, Configure and Upgrade
Tested with NSX 2.5
> Added examples for Install, Configure and Upgrade

- policy-ansible-for-nsxt/README.md
- policy-ansible-for-nsxt/library/nsxt_ip_pool.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_ip_pool.yml
> Add support to create/delete IpPoolStaticSubnet

- library/nsxt_controller_manager_auto_deployment_facts.py
- test_controller_manager_auto_deployment_facts.yml
Created and added facts module for cluster node VM deployment.
This solves bugzilla #2508089
> Facts module for cluster node VM deployment

- library/nsxt_controller_manager_auto_deployment.py
Disk provisioning example is added to the example of .py file.
> Added disk provisioning example

- library/nsxt_fabric_compute_managers.py
In nsxt_fabric_compute_manager module documentation is done
for description parameter whose support is added.
This completes Bugzilla: #2510123
> Added documentation for description

- answerfile.yml
Transport node profile in answerfile is updated.
This solves Bugzilla #2517319
> Updated answerfile

- policy-ansible-for-nsxt/library/nsxt_policy_group.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_ip_block.yml
- policy-ansible-for-nsxt/unit_tests/test_nsxt_policy_group.yml
- policy-ansible-for-nsxt/unit_tests/test_nsxt_security_policy.yml
Signed-off-by: Gautam Verma <gautam94verma@gmail.com>x
> Correct comments in playbooks and update sec_policy unit_test

- policy-ansible-for-nsxt/library/nsxt_tier0.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
> Add missing attrs in tier0

- policy-ansible-for-nsxt/library/nsxt_tier1.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
- policy-ansible-for-nsxt/unit_tests/test_nsxt_tier1.yml
Also fix a comment in unit test of tier0
> Add missing attrs in tier1 module

- policy-ansible-for-nsxt/library/nsxt_segment.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_segment.yml
> Add missing attrs in nsxt_segment

- policy-ansible-for-nsxt/library/nsxt_security_policy.py
- policy-ansible-for-nsxt/unit_tests/test_nsxt_security_policy.yml
> Add missing attrs for rules in security_policy

- policy-ansible-for-nsxt/library/nsxt_bfd_config.py
- policy-ansible-for-nsxt/library/nsxt_tier0.py
- policy-ansible-for-nsxt/module_utils/nsxt_base_resource.py
- policy-ansible-for-nsxt/module_utils/nsxt_resource_urls.py
- policy-ansible-for-nsxt/unit_tests/test_bfd_config.yaml
- policy-ansible-for-nsxt/unit_tests/test_nsxt_tier0.yml
We add the support to
1. specify BFD Peers in T0
2. Update/Delete BFD Config
Jira: #50034
> Add support for T0 BFD Peer & Config

- policy-ansible-for-nsxt/library/nsxt_vm_tags.py
- policy-ansible-for-nsxt/module_utils/nsxt_resource_urls.py
- policy-ansible-for-nsxt/unit_tests/test_vm_tags.yaml
This Module does not consume the NSXTBaseRealizableResource
because it is not a realizable resource. We directly use
the policy_communicatore for it to function
Jira: #50034
> Add Module to allow VM Tags Update

- answerfile.yml
- test_transport_nodes_edge.yml
- test_transport_nodes_host.yml
This CL updates TN examples. We have separate examples for host and Edge TN.
> TN examples updated

- library/nsxt_manager_auto_deployment.py
While deleting autodeployed node, node was required before.
Node id is replaced with node name using get api call.
> Node name to id while deleting auto deploy node

- library/nsxt_transport_nodes.py
Before FN-TN unification, fabric node id was a mandatory field
but now it is not. Today node_id is same as that of tn id.
Thus there is no point in having that. Thus removing node_id.
node_id given is same as that of TN id.
The module was not getting updated due as revision was required
in node_deployment_request field also. This CL solves it.
Testing done:
Created a Host TN successfully.
Updated its description. 4 times successfuly.
Deleted the TN successfully.
> Node_id removed and revision issue

- library/nsxt_principal_identities.py
- test_principal_identities.yml
Update functionality is added
Signed-off-by: Kommireddy Akhilesh<akhilshkommireddy2412@gmail.com>
> Updating principal id module

- library/nsxt_certificates.py
- library/nsxt_edge_clusters.py
Added optional parameters in the .py file.
Added description in nsxt_edge_cluster.py
Added tags in nsxt_certificates.py
This solves bugzilla 2525243, 2527876
> Adding optional parameters

- library/nsxt_transport_nodes.py
Added tags field in TN module and changed transport zone endpoint
auto updation.
> Added tags field in TN

- library/nsxt_edge_clusters.py
- library/nsxt_transport_nodes.py
Added optional parameters to TN module and edge custer module
Also added support to update description.
Added NODE_READY as a success state while deploying edge cluster.
Testing done:
Tested if added parameters are being passed to ansible module.
Checked for TN and Edge cluster modules.
> Adding optional params to TN module and edge cluster

- library/nsxt_transport_zones.py
Added support for tags field in TZ module.
Documentation is updated accordingly.
> Adding support for tags in the TZ module

- library/nsxt_upgrade_prechecks.py
Added support to exit from pre upgrade polling loop
when prechecks are aborted.
Adding timeout field in documentation.
> Exiting from polling loop when prechecks abort

- library/nsxt_upgrade_groups.py
- library/nsxt_upgrade_postchecks.py
- test_upgrade_postchecks.yml
Upgrade group was failing as update parameter was not being
passed correctly. Changed the parameter to correct one.
Changed few errors in upgrade post check module.
Updated documentation.
> Upgrade group update failure

- library/nsxt_logical_router_static_routes.py
- test_logical_router_static_route.yml
Removed bugs around update functionality.
Added parameters description, display_name and tags.
> nsxt_logical_router_static_routes updated

- library/nsxt_logical_router_ports.py
Added optional params in nsxt_logical_router_ports.
Few params were taking boolean as input type. Python doesn't have
boolean keyword. converted it to bool.
> Added optional params in nsxt_logical_router_ports

- library/nsxt_policy_tier1.py
Rename enabled to bgp_enabled per policy API changes under
route_redistribution_config under locale_service under tier1
Issue: #2535602
> Update locale_service attr per policy API change

- README.md
Updates include:
- recommended Python and Ansible minimum versions as per QE testbed
- correcting the links and instructions to download and work with
the zip for v3.0.0
> Update Readme with v3.0.0 branch identifiers

- README.md
> Update Readme with latesst nsx-t and ansible version

- README.md
- library/nsxt_policy_segment.py
- library/nsxt_policy_tier1.py
- module_utils/nsxt_base_resource.py
- module_utils/policy_communicator.py
Cherry picking the commits from dev to master to sync
> Sync cherry dev to master

- module_utils/nsxt_base_resource.py
> Correct accepted_error_code to del resource

- module_utils/policy_communicator.py
> Enable usage of vIDM remote header

- library/nsxt_policy_gateway_policy.py
- module_utils/nsxt_base_resource.py
- module_utils/nsxt_resource_urls.py
- module_utils/policy_resource_specs/security_policy.py
- unit_tests/test_nsxt_policy_gateway_policy.yml
> Support Gateway Policy configuration

- library/nsxt_cluster_profiles.py
- library/nsxt_cluster_profiles_facts.py
- test_cluster_profiles.yml
- test_cluster_profiles_facts.yml
This CL adds modules for create, update, list and delete
operations on cluster profiles.
Signed-off-by: Kommireddy Akhilesh<akhileshk@vmware.com>
> Cluster Profile module

- library/nsxt_policy_l2_bridge_ep_profile.py
- module_utils/nsxt_base_resource.py
- module_utils/nsxt_resource_urls.py
- module_utils/policy_resource_specs/l2_bridge_ep_profile.py
- unit_tests/test_nsxt_policy_l2_bridge_ep_profile.yml
> Add L2 Bridge Endpoint Profile support

- library/nsxt_policy_bfd_profile.py
- module_utils/nsxt_base_resource.py
- module_utils/nsxt_resource_urls.py
- unit_tests/test_nsxt_policy_bfd_profile.yaml
This change is introduces the NSX-t 3.1.1
Issue: #2666696
> Rename BFDConfig to BFDProfiles

- library/nsxt_policy_segment.py
> Make address_bindings param in Seg Port list attr'

- library/nsxt_policy_tier0.py
> Make route_filtering list under BGP neighbor

- README.md
- library/nsxt_policy_tier0.py
- module_utils/nsxt_base_resource.py
- unit_tests/test_nsxt_policy_tier0.yml
> Update BFD Config to Profile in Tier0

- module_utils/nsxt_base_resource.py
> Use display_name as ID if ID not specified

- plugins/modules/nsxt_policy_segment.py
This fixes the nsxt_policy_segment module after the move to a collection as described in #364 
Signed-off-by: Leon Vliegenthart <leon@vliegenthart.me>
> Fix imports on nsxt_policy_segment.py

- README.md
- galaxy.yml
Issue: #290
Internal JIRA: NSXT-100155
Signed-off-by: Gautam Verma vermag@vmware.com
Signed-off-by: Gautam Verma gautam94verma@gmail.com
> Update README.md to move to Ansible Collection

- library/nsxt_local_manager_registration.py
- library/nsxt_local_managers_facts.py
- library/nsxt_transport_node_collections.py
- test_local_managers_facts.yml
Added a new module nsxt_local_managers_facts and added support for optional parameters in nsxt_local_manager_registration module
> Federation bug fixes

- plugins/modules/nsxt_local_managers_facts.py
Rectified import statements as per new collections structure
> Rectified import statements

- README.md
- plugins/module_utils/vcenter_utils.py
- plugins/modules/nsxt_transport_node_collections.py
- plugins/modules/nsxt_transport_node_profiles.py
- plugins/modules/nsxt_transport_nodes.py
- plugins/modules/nsxt_transport_zones.py
- plugins/modules/nsxt_uplink_profiles.py
- tests/playbooks/mp/test_transport_node_profiles.yml
- tests/playbooks/mp/test_transport_nodes.yml
Multiple Bug Fixes.
Description:
Following Bugs were fixed.
BugID     Bug Description
2619445 - nsxt_transport_nodes modules needs updates based on new spec
2648943 - updation of only tags is not supported by 'nsxt_transport_nodes' module
2825054 - Create Edge transport node using ansible module fails
2731783 - Getting "info from vCenter: [SSL: CERTIFICATE_VERIFY_FAILED]" when deploying 2nd and 3rd NSX-T managers
2643929 - "tags" field is not support by "nsxt_transport_node_profiles" module
2645685 - "tags" field is not supported by "nsxt_transport_node_collections" module
2645684 - Updating 'Description' and 'Transport Node Profile' fields in "nsxt_transport_node_collections" module fails
2619365 - nsxt_transport_node_profiles.py fails if transport_zone_endpiont is not provided outside …
> Multiple Bug Fixes.

- README.md
Also fix the ansible-galaxy command to install the playbooks
Issue: #385
> Update README to include v3.2.0

- plugins/modules/nsxt_manager_auto_deployment.py
BugID        Description
2731783 - Getting "info from vCenter: [SSL: CERTIFICATE_VERIFY_FAILED]" when deploying 2nd and 3rd NSX-T managers
> Auto Deployment Module Modified

- README.md
> Update README -> minimum pip3 and ansible-galaxy version

- plugins/modules/nsxt_vm_tags.py
The original aim of this PR was to fix Issue: #445 but it was fixed by https://github.com/vmware/ansible-for-nsxt/pull/439.
Now this PR only makes cosmetic improvements
> Fix bug when multiple tags are present with same scope

- plugins/module_utils/vmware_nsxt.py
> Pagination for Proton APIs

- plugins/module_utils/vmware_nsxt.py
Ansible manager facts modules are failing with "Input byte array has incorrect ending byte at 20" error
Description: Cursor key value pair in request param was getting appended instead of updation in the next iteration after pagination was introduced for MP modules.
For example:     url = "https://10.196.179.73/api/v1/logical-switches?cursor=0041-8605035095901123965.-7350981255833053930MTY4NDkyMzAzMTE4Mw==&cursor=0041-5880602792106442526.-6188807095818619501MTY4NDkyMzExOTgxNw=="
Fix provided: To resolve this issue, now we are using python in build libraries instead of having our own logic to update the cursor
from urllib.parse import urlparse, parse_qs, urlencode, unquote, urlunparse
BugId:3214989
> Ansible manager facts modules

- plugins/modules/nsxt_transport_nodes.py
Added Edge Transport Node example in documentation
Bug Id: 3287588
> Added Edge Transport Node example

- plugins/module_utils/vmware_nsxt.py
NSX pagination is not handled correctly because redundant API calls are being made on NSX. Moreover, URL parsing and unparsing may introduce issues that are hard to debug. This patch uses iterative approach to handle NSX pagination and removes the code that parses the URL to be queried for better reliability
Issue: #3404438
> Fix pagination for MP modules
